name: ci
on:
  pull_request:
    branches: [dev, main]
jobs:
  fe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - run: npm install
      - run: npm run typecheck:fe
      - run: npm run lint:fe
      - run: npm run build:fe